{% set name = "pillow-heif" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pillow_heif-{{ version }}.tar.gz
  sha256: 6c0c5f81a780185bbddc56e0d5537c53aa6cb5fb6018f5a60534a47c53f5455d

build:
  number: 1
  script: |
    {% if win %}
    :: libheif on Windows ships heif.lib, but the build looks for libheif.lib
    if not exist "%LIBRARY_LIB%\libheif.lib" (
      copy "%LIBRARY_LIB%\heif.lib" "%LIBRARY_LIB%\libheif.lib"
    )
    {% endif %}
    {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=67.8
    - wheel
    - pip
    - libheif
  run:
    - python
    - pillow >=10.1.0

test:
  imports:
    - pillow_heif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bigcat88/pillow_heif
  summary: Python interface for libheif library
  dev_url: https://github.com/bigcat88/pillow_heif
  license: GPL-2.0-or-later AND EPL-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE.txt
    - tests/images/heif_other/nokia/COPYRIGHT.txt

extra:
  recipe-maintainers:
    - jeongseok-meta
    - rxm7706
